### ISSUE TITLE
Calculate SVF is broken in app

### ISSUE THREAD

**Issue by nicholas512** [geocryology/HorizonPy#23]
Open image 3
attempt to rotate 
get error:
```Traceback (most recent call last):
  File "C:\Users\Nick\Anaconda3\envs\horpy3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "c:\users\nick\src\horizonpy\horizonpy\quickhorizon\SkyViewFactorDialog.py", line 73, in redraw
    self.rot, = plot_rotated_points(self.pts_az, self.pts_hor, self.surface_asp, self.surface_dip, self.ax)
  File "c:\users\nick\src\horizonpy\horizonpy\skyview.py", line 27, in plot_rotated_points
    rt = rotate_horizon(azi, hor, asp, dip)
  File "c:\users\nick\src\horizonpy\horizonpy\skyview.py", line 379, in rotate_horizon
    overhanging = test_overhang(coords[0], coords[1])
  File "c:\users\nick\src\horizonpy\horizonpy\skyview.py", line 264, in test_overhang
    L = LinearRing(xy)  # horizon line
  File "C:\Users\Nick\Anaconda3\envs\horpy3\lib\site-packages\shapely\geometry\polygon.py", line 55, in __init__
    self._set_coords(coordinates)
  File "C:\Users\Nick\Anaconda3\envs\horpy3\lib\site-packages\shapely\geometry\polygon.py", line 70, in _set_coords
    ret = geos_linearring_from_py(coordinates)
  File "shapely\speedups\_speedups.pyx", line 401, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: GEOSGeom_createLinearRing_r returned a NULL pointer```

**Comment by nicholas512** [comment]
fixed in a2f6ca2
